version: 1
datastore:
  user: root
  password: root
  hostname: kafka-lab.westus2.cloudapp.azure.com
  port: 3306
  db: events
events:
  hostname: kafka-lab.westus2.cloudapp.azure.com
  port: 9092
  topic: events
